[package]
name = "rav1e_asm_x86"
version = "0.0.0"
authors = ["Thomas Daede <tdaede@xiph.org>"]
edition = "2021"
rust-version = "1.70.0"

[build-dependencies]
cc = { version = "1.0", features = ["parallel"] }
built = "0.7.1"
nasm-rs = { version = "0.2", features = ["parallel"] }
