name: rav1e

on:
  push:
    branches:
      - master
      - 0.*
  pull_request:
    branches:
      - master
      - 0.*

jobs:
  rustfmt-clippy:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4
      - uses: ilammy/setup-nasm@v1
      - name: Install stable
        uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy, rustfmt
      - name: Run rustfmt
        run: |
          cargo fmt -- --check --verbose
      - name: Run clippy
        uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: -- -D warnings --verbose -A clippy::wrong-self-convention -A clippy::many_single_char_names -A clippy::upper-case-acronyms

  codecov:
    runs-on: ubuntu-22.04

    needs: rustfmt-clippy

    steps:
      - uses: actions/checkout@v4
      - name: Install Rust with LLVM tools
        uses: dtolnay/rust-toolchain@stable
        with:
          components: llvm-tools-preview
      - uses: ilammy/setup-nasm@v1
      - name: Install libdav1d dependencies
        run: |
          sudo apt update
          sudo apt install meson ninja-build
      - name: Install grcov
        env:
          LINK: https://github.com/mozilla/grcov/releases/latest/download
        run: |
          curl -L "$LINK/grcov-x86_64-unknown-linux-musl.tar.bz2" |
          tar xj -C $HOME/.cargo/bin
      - name: Install Intel SDE
        uses: petarpetrovt/setup-sde@v2.3

      - name: Run tests with coverage
        env:
          CARGO_INCREMENTAL: 0
          LLVM_PROFILE_FILE: "rav1e-%p-%m.profraw"
          RUSTFLAGS: >
            -Cinstrument-coverage -Ccodegen-units=1 -Clink-dead-code
            -Coverflow-checks=off
          RUSTDOCFLAGS: >
            -Cinstrument-coverage -Ccodegen-units=1 -Clink-dead-code
            -Coverflow-checks=off
          CARGO_TARGET_X86_64_UNKNOWN_LINUX_GNU_RUNNER: >
            ${{ env.SDE_PATH }}/sde -icx --
        run: |
          cargo test --workspace --features=decode_test,decode_test_dav1d,quick_test

      - name: Run grcov
        run: |
          grcov . --binary-path ./target/x86_64-unknown-linux-gnu/debug/  -s . \
                -t lcov --branch --ignore-not-existing --ignore "/*" \
                --ignore "../*" --ignore "target/*" --ignore "examples/*" \
                --ignore "tests/*" --ignore "src/test_encode_decode/*" \
                --ignore "src/x86/*" --ignore "src/ext/x86/*" \
                --excl-line "grcov-excl-line|.*unreachable.*" \
                --ignore "tools/*" --ignore "crates/*" -o lcov.info
      - name: Codecov upload
        uses: codecov/codecov-action@v4
        with:
          files: lcov.info

  build-unix:
    strategy:
      matrix:
        conf:
          - name: beta-build
            toolchain: beta
          - name: 1.70.0-tests
            toolchain: 1.70.0
          - name: aom-tests
            toolchain: stable
          - name: dav1d-tests
            toolchain: stable
          - name: dav1d-tests-arm64
            toolchain: stable
          - name: no-asm-tests
            toolchain: stable
          - name: bench
            toolchain: stable
          - name: doc
            toolchain: stable
          - name: cargo-c
            toolchain: stable
          - name: check-no-default
            toolchain: stable
          - name: check-extra-feats
            toolchain: stable
          - name: check-unstable-feats
            toolchain: stable
          - name: fuzz
            toolchain: stable

    env:
      RUST_BACKTRACE: full
      CARGO_INCREMENTAL: 0

    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4
      - name: Set no-asm-tests env vars
        if: matrix.conf.name == 'no-asm-tests'
        run: |
          echo "name=RAV1E_CPU_TARGET::rust" >> $GITHUB_ENV
      - name: Install dependencies
        if: matrix.conf.name != 'dav1d-tests-arm64'
        run: |
          sudo sed -i 's/jammy/lunar/g' /etc/apt/sources.list
          sudo rm /etc/apt/sources.list.d/*.list
          sudo apt update
          sudo apt install nasm libaom-dev meson ninja-build nasm
      - name: Install cargo-c
        if: matrix.conf.name == 'cargo-c'
        env:
          LINK: https://github.com/lu-zero/cargo-c/releases/latest/download
        run: |
          curl -L "$LINK/cargo-c-x86_64-unknown-linux-musl.tar.gz" |
          tar xz -C $HOME/.cargo/bin

      - name: Install ${{ matrix.conf.toolchain }}
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.conf.toolchain }}
      - name: Install aarch64 toolchain, qemu-user and libdav1d deps
        if: matrix.conf.name == 'dav1d-tests-arm64'
        env:
          LINK: http://ports.ubuntu.com/ubuntu-ports/pool
        run: |
          rustup target add aarch64-unknown-linux-gnu
          { echo 'deb [arch=amd64] http://azure.archive.ubuntu.com/ubuntu lunar main universe'
            echo 'deb [arch=amd64] http://azure.archive.ubuntu.com/ubuntu lunar-updates main universe'
            echo 'deb [arch=arm64] http://azure.ports.ubuntu.com/ lunar main universe'
          } | sudo tee /etc/apt/sources.list
          sudo dpkg --add-architecture arm64
          sudo apt update
          sudo apt install qemu-user gcc-aarch64-linux-gnu meson ninja-build nasm
      - name: Cache cargo registry and compiled dependencies
        uses: Swatinem/rust-cache@v2
      - name: Run 1.70.0 tests
        if: matrix.conf.toolchain == '1.70.0' && matrix.conf.name == '1.70.0-tests'
        run: |
          cargo test --workspace --verbose \
                     --features=decode_test,decode_test_dav1d,quick_test,capi
      - name: Run aom tests
        if: matrix.conf.toolchain == 'stable' && matrix.conf.name == 'aom-tests'
        run: |
          cargo test --workspace --verbose --release \
                     --features=decode_test \
                     --color=always -- --color=always --ignored
      - name: Run dav1d tests
        if: matrix.conf.toolchain == 'stable' && (matrix.conf.name == 'dav1d-tests' || matrix.conf == 'no-asm-tests')
        run: |
          cargo test --workspace --verbose --release \
                     --features=decode_test_dav1d \
                     --color=always -- --color=always --ignored
      - name: Run dav1d tests (arm64)
        if: matrix.conf.name == 'dav1d-tests-arm64'
        env:
          CARGO_TARGET_AARCH64_UNKNOWN_LINUX_GNU_RUNNER: qemu-aarch64 -L /usr/aarch64-linux-gnu
          CARGO_TARGET_AARCH64_UNKNOWN_LINUX_GNU_RUSTFLAGS: -Clinker=aarch64-linux-gnu-gcc
          PKG_CONFIG_PATH: /usr/lib/aarch64-linux-gnu/pkgconfig
          PKG_CONFIG_SYSROOT_DIR: /
        run: |
          cargo test --lib --verbose --release --target=aarch64-unknown-linux-gnu \
                     --no-default-features --features=asm,decode_test_dav1d -- \
                     --include-ignored
      - name: Run build
        if: matrix.conf.name == 'beta-build'
        run: |
          cargo build --verbose
      - name: Run bench
        if: matrix.conf.toolchain == 'stable' && matrix.conf.name == 'bench'
        run: |
          cargo bench --features=bench --no-run --verbose
      - name: Run doc
        if: matrix.conf.toolchain == 'stable' && matrix.conf.name == 'doc'
        run: |
          cargo doc --verbose --no-deps
      - name: Check no default features
        if: matrix.conf.toolchain == 'stable' && matrix.conf.name == 'check-no-default'
        run: |
          cargo check --no-default-features
      - name: Check extra features
        if: matrix.conf.toolchain == 'stable' && matrix.conf.name == 'check-extra-feats'
        run: |
          cargo check --features=check_asm,capi,dump_lookahead_data,serialize,bench,tracing --all-targets
      - name: Check extra features
        if: matrix.conf.toolchain == 'stable' && matrix.conf.name == 'check-unstable-feats'
        run: |
          cargo check --features=unstable,channel-api
      - name: Run cargo-c
        if: matrix.conf.name == 'cargo-c'
        env:
          CARGO_REGISTRIES_CRATES_IO_PROTOCOL: git
        run: |
          cargo fetch
          cargo cbuild --offline
      - name: Install cargo-fuzz
        if: matrix.conf.name == 'fuzz'
        run: |
          cargo install cargo-fuzz
      - name: Run cargo-fuzz
        if: matrix.conf.name == 'fuzz'
        run: |
          cargo fuzz build --sanitizer none

      - name: Run unit tests
        if: matrix.conf.name == 'no-asm-tests'
        run: |
          cargo test --workspace --verbose

  build-macos:
    strategy:
      matrix:
        conf:
          - name: cargo-build
            target: x86_64-apple-darwin
          - name: cargo-test
            target: x86_64-apple-darwin
          - name: cargo-c
            target: x86_64-apple-darwin
          - name: cargo-build
            target: aarch64-apple-darwin
          - name: cargo-c
            target: aarch64-apple-darwin

    env:
      RUST_BACKTRACE: full
      CARGO_INCREMENTAL: 0

    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install nasm
        run: |
          brew install nasm
      - name: Install cargo-c
        if: matrix.conf.name == 'cargo-c'
        run: |
          brew install cargo-c
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          target: ${{ matrix.conf.target }}
      - name: Cache cargo registry and compiled dependencies
        uses: Swatinem/rust-cache@v2
      - name: Build
        if: matrix.conf.name == 'cargo-build'
        run: |
          cargo build --release --target=${{ matrix.conf.target }}
      - name: Test
        if: matrix.conf.name == 'cargo-test'
        run: |
          cargo test --workspace --verbose --target=${{ matrix.conf.target }}
      - name: Run cargo-c
        if: matrix.conf.name == 'cargo-c'
        env:
          CARGO_REGISTRIES_CRATES_IO_PROTOCOL: git
        run: |
          cargo fetch
          cargo cbuild --target=${{ matrix.conf.target }} --offline

  build-windows:
    strategy:
      matrix:
        conf:
          - name: cargo-build
            target: x86_64-pc-windows-msvc
          - name: cargo-test
            target: x86_64-pc-windows-msvc
          - name: cargo-c
            target: x86_64-pc-windows-gnu

    env:
      RUST_BACKTRACE: full
      CARGO_INCREMENTAL: 0

    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ilammy/setup-nasm@v1
      - name: Install stable-${{ matrix.conf.target }}
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable-${{ matrix.conf.target }}
      - name: Install cargo-c
        if: matrix.conf.name == 'cargo-c'
        run: |
          $LINK = "https://github.com/lu-zero/cargo-c/releases/latest/download"
          $CARGO_C_FILE = "cargo-c-windows-msvc"
          curl -LO "$LINK/$CARGO_C_FILE.zip"
          7z e -y "$CARGO_C_FILE.zip" -o"${env:USERPROFILE}\.cargo\bin"
      - name: Cache cargo registry and compiled dependencies
        uses: Swatinem/rust-cache@v2
      - name: Build
        if: matrix.conf.name == 'cargo-build'
        run: |
          cargo build --release
      - name: Test
        if: matrix.conf.name == 'cargo-test'
        run: |
          cargo test --workspace --verbose
      - name: Run cargo-c
        if: matrix.conf.name == 'cargo-c'
        env:
          CARGO_REGISTRIES_CRATES_IO_PROTOCOL: git
        run: |
          cargo fetch
          cargo cbuild --offline
